/**
 * ============================================
 * METAL INVENTORY SERVICE
 * ============================================
 */

import api from './api';

export interface MetalStock {
  id: string;
  metalType: string;
  purity: number;
  form: string;
  grossWeight: number;
  pureWeight: number;
  location?: string;
  batchNumber?: string;
  createdAt: string;
  updatedAt: string;
}

export interface MetalTransaction {
  id: string;
  transactionType: string;
  metalType: string;
  purity: number;
  form: string;
  grossWeight: number;
  pureWeight: number;
  rate?: number;
  totalValue?: number | null;
  createdAt: string;
  createdBy?: {
    name: string;
  };
  vendorId?: string | null;
  vendor?: { id: string; name: string; uniqueCode: string; creditBalance?: number } | null;
  // Payment fields (only populated for billable PURCHASE rows).
  isBillable?: boolean | null;
  paymentMode?: string | null;       // 'CASH' | 'NEFT' | 'BOTH'
  paymentStatus?: string | null;     // 'COMPLETE' | 'HALF' | 'PENDING'
  amountPaid?: number | null;
  cashAmount?: number | null;
  neftAmount?: number | null;
  neftUtr?: string | null;
  neftBank?: string | null;
  neftDate?: string | null;
  /** Vendor credit applied to / generated by this purchase. */
  creditApplied?: number | null;
  creditGenerated?: number | null;
  payments?: MetalPayment[];
}

export interface MetalPayment {
  id: string;
  transactionId: string;
  amount: number;
  paymentMode: string;
  cashAmount?: number | null;
  neftAmount?: number | null;
  neftUtr?: string | null;
  neftBank?: string | null;
  neftDate?: string | null;
  notes?: string | null;
  creditApplied?: number | null;
  creditGenerated?: number | null;
  recordedAt: string;
  recordedBy?: { id: string; name: string; email?: string } | null;
}

export interface SettleMetalPaymentRequest {
  amount: number;
  paymentMode: string;
  cashAmount?: number;
  neftAmount?: number;
  neftUtr?: string;
  neftBank?: string;
  neftDate?: string;
  notes?: string;
  /** Vendor credit to apply on top of `amount` (counts toward balance reduction). */
  creditApplied?: number;
}

export interface MeltingBatch {
  id: string;
  batchNumber: string;
  inputMetals: any;
  totalInputWeight: number;
  outputPurity: number;
  outputWeight: number;
  wastageWeight: number;
  wastagePercent: number;
  meltedAt: string;
  meltedBy?: {
    name: string;
  };
}

export interface MetalRate {
  id: string;
  metalType: string;
  purity: number;
  ratePerGram: number;
  effectiveDate: string;
  source?: string;
}

export async function getAllMetalStock(filters?: {
  metalType?: string;
  purity?: number;
}): Promise<MetalStock[]> {
  const response = await api.get('/metal/stock', { params: filters });
  return response.data.data;
}

export async function getMetalStockSummary() {
  const response = await api.get('/metal/stock/summary');
  return response.data.data;
}

export async function createMetalStock(data: any) {
  const response = await api.post('/metal/stock', data);
  return response.data.data;
}

export async function createMetalTransaction(data: any) {
  const response = await api.post('/metal/transactions', data);
  return response.data.data;
}

/**
 * Update an existing metal transaction. Reverses old stock effect and applies
 * the new one server-side. Backend rejects edits to billable rows with payment
 * activity — settle/void via the Settle modal instead.
 */
export async function updateMetalTransaction(id: string, data: any) {
  const response = await api.patch(`/metal/transactions/${id}`, data);
  return response.data.data;
}

/**
 * Delete a metal transaction. Server reverses stock + vendor-credit effects
 * before deleting. ADMIN only. Rejected if the row has settlement entries.
 */
export async function deleteMetalTransaction(id: string) {
  const response = await api.delete(`/metal/transactions/${id}`);
  return response.data.data;
}

export async function getAllMetalTransactions(filters?: any): Promise<MetalTransaction[]> {
  const response = await api.get('/metal/transactions', { params: filters });
  return response.data.data;
}

export async function createMeltingBatch(data: any) {
  const response = await api.post('/metal/melting-batches', data);
  return response.data.data;
}

export async function getMeltingBatches(): Promise<MeltingBatch[]> {
  const response = await api.get('/metal/melting-batches');
  return response.data.data;
}

export async function getCurrentMetalRates(): Promise<MetalRate[]> {
  const response = await api.get('/metal/rates');
  return response.data.data;
}

export async function createMetalRate(data: any) {
  const response = await api.post('/metal/rates', data);
  return response.data.data;
}

export async function settleMetalPayment(
  id: string,
  data: SettleMetalPaymentRequest
): Promise<MetalTransaction> {
  const response = await api.patch(`/metal/transactions/${id}/payment`, data);
  return response.data.data;
}

export async function getMetalPayments(transactionId: string): Promise<MetalPayment[]> {
  const response = await api.get(`/metal/transactions/${transactionId}/payments`);
  return response.data.data;
}

/**
 * Download a metal-transaction Excel export. Forwards the same filters
 * as the list endpoint, plus an optional `taxClass` to scope to billable
 * or non-billable rows for Income-Tax filing.
 */
export async function exportMetalTransactionsXlsx(filters?: {
  metalType?: string;
  transactionType?: string;
  startDate?: string;
  endDate?: string;
  taxClass?: 'BILLABLE' | 'NON_BILLABLE';
}): Promise<Blob> {
  const response = await api.get('/metal/transactions/export', {
    params: filters,
    responseType: 'blob',
  });
  return response.data as Blob;
}
