#Requires -RunAsAdministrator
<#
.SYNOPSIS
    One-time setup: registers a scheduled task 'AtivaDeploy' on this machine
    that runs scripts\deploy.ps1 with highest privileges, triggered on demand.
.DESCRIPTION
    Why: SSH sessions on Windows run with a filtered (non-elevated) token.
    Since deploy.ps1 requires admin, we wrap it in a scheduled task so any
    SSH session can trigger the elevated deploy via:
        schtasks /run /tn "AtivaDeploy"

    After registration, every run of the task is logged to:
        C:\ProgramData\AtivaDeploy\deploy.log

    Run this once from an elevated PowerShell on the prod PC.
#>

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

$TaskName    = 'AtivaDeploy'
$ProjectRoot = Split-Path -Parent (Split-Path -Parent $PSCommandPath)
$DeployPs1   = Join-Path $ProjectRoot 'scripts\deploy.ps1'
$LogDir      = 'C:\ProgramData\AtivaDeploy'
$LogFile     = Join-Path $LogDir 'deploy.log'
$WrapperPs1  = Join-Path $LogDir 'run-deploy.ps1'

Write-Host "==> Registering scheduled task '$TaskName'" -ForegroundColor Cyan
Write-Host "    Project root: $ProjectRoot"
Write-Host "    deploy.ps1  : $DeployPs1"
Write-Host "    Log file    : $LogFile"

if (-not (Test-Path $DeployPs1)) {
    Write-Host "[FAIL] deploy.ps1 not found at $DeployPs1" -ForegroundColor Red
    exit 1
}

# Log directory (world-readable so non-admin SSH sessions can tail the log)
New-Item -ItemType Directory -Path $LogDir -Force | Out-Null

# Wrapper script the task will actually execute.
# Uses Start-Transcript to capture Write-Host output under Task Scheduler (which
# has no interactive host). On PS 5.1 Start-Transcript writes UTF-16 LE; readers
# should use 'Get-Content -Encoding Unicode' (or Notepad auto-detects).
# We do NOT merge streams with *>&1 here, because deploy.ps1 uses
# ErrorActionPreference=Stop, and many native commands (vite, tsc) write
# coloured output to stderr, which would otherwise become a terminating error.
$wrapper = @"
# Auto-generated by register-deploy-task.ps1 - do not edit by hand.
Set-Location '$ProjectRoot'
`$ts = Get-Date -Format 'yyyy-MM-dd HH:mm:ss'
Add-Content -Path '$LogFile' -Value '' -Encoding UTF8
Add-Content -Path '$LogFile' -Value "===== Deploy started: `$ts =====" -Encoding UTF8
try { Start-Transcript -Path '$LogFile' -Append -Force | Out-Null } catch {}
`$code = 0
try {
    & '$DeployPs1'
    `$code = `$LASTEXITCODE
    if (`$null -eq `$code) { `$code = 0 }
} catch {
    Write-Host "===== Deploy threw: `$(`$_.Exception.Message) ====="
    `$code = 99
}
try { Stop-Transcript | Out-Null } catch {}
Add-Content -Path '$LogFile' -Value "===== Deploy finished: exit=`$code at `$(Get-Date -Format 'yyyy-MM-dd HH:mm:ss') =====" -Encoding UTF8
exit `$code
"@
$wrapper | Out-File -LiteralPath $WrapperPs1 -Encoding utf8 -Force
Write-Host "    Wrapper     : $WrapperPs1"

# The task runs as the local admin user 'pc' with S4U logon (no password stored)
# + RunLevel Highest. This lets the same user trigger the task from any session
# -- including a non-elevated SSH session -- with full admin rights.
$runAsUser = "$env:USERDOMAIN\$env:USERNAME"

$action = New-ScheduledTaskAction `
    -Execute 'powershell.exe' `
    -Argument "-NoProfile -ExecutionPolicy Bypass -File `"$WrapperPs1`""

$principal = New-ScheduledTaskPrincipal `
    -UserId $runAsUser `
    -LogonType S4U `
    -RunLevel Highest

$settings = New-ScheduledTaskSettingsSet `
    -AllowStartIfOnBatteries `
    -DontStopIfGoingOnBatteries `
    -StartWhenAvailable `
    -ExecutionTimeLimit ([TimeSpan]::FromMinutes(30))

# Remove any stale version of the task
if (Get-ScheduledTask -TaskName $TaskName -ErrorAction SilentlyContinue) {
    Unregister-ScheduledTask -TaskName $TaskName -Confirm:$false
    Write-Host "    Removed existing '$TaskName' task"
}

Register-ScheduledTask `
    -TaskName $TaskName `
    -Action $action `
    -Principal $principal `
    -Settings $settings `
    -Description 'Builds + deploys Ativa Jewels app (backend, frontend, tunnel). Triggered on-demand via schtasks /run.' | Out-Null

Write-Host "    Runs as    : $runAsUser (S4U, Highest)"

Write-Host "[OK] Scheduled task '$TaskName' registered" -ForegroundColor Green
Write-Host ''
Write-Host 'From any PowerShell session (including SSH), you can now run:' -ForegroundColor Cyan
Write-Host "    schtasks /run /tn `"$TaskName`"" -ForegroundColor Yellow
Write-Host ''
Write-Host 'Tail the deploy log with:' -ForegroundColor Cyan
Write-Host "    Get-Content `"$LogFile`" -Wait -Tail 50" -ForegroundColor Yellow
Write-Host ''
Write-Host 'Try it now (from this elevated prompt):' -ForegroundColor Cyan
Write-Host "    schtasks /run /tn `"$TaskName`"" -ForegroundColor DarkGray
